
language: python

python:
  - "3.3"
  - "2.7"
  - "pypy"


install:
  - pip install -r requirements_test.txt
  - pip install coveralls


script: coverage run --source=yo_payments setup.py test
after_success:
  coveralls